baseURL: 'https://benotdeceived.org/Hugo-Mainroad/'
languageCode: en-us
title: My New Hugo Site
theme: ["hugo-admonitions", "mainroad"]

pagination:
  pagerSize: 10

taxonomies:
  category: categories
  tag: tags
  topic: topics
  series: series
  chapter: chapters

enableRobotsTXT: true
pluralizeListTitles: false
contentDir: "hugo"
ignoreFiles: \/Templates\/*
enableGitInfo: true

frontmatter:
  date:
  - date
  - lastmod

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

params:
  description: "Using Obsidian as a CMS for Hugo using the Mainroad Theme."
  author: Hugo-Mainroad
#  email: info@just-me.org
  readmore: true
  authorbox: false
  toc: true
  pager: true
  post_meta:
    - date
    - categories
  dateformat: "January 01, 2006 03:04 PM"
  googleFontsLink: https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700
#  customCSS:
#    - 'css/custom.css'
#  customJS:
#    - 'js/custom.js'
  style:
    vars:
      highlightColor:  '#84ea90'
      fontFamilyPrimary: "'Open Sans', Helvetica, Arial, sans-serif"
      fontFamilySecondary: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace
  logo:
    image: "/images/logo.png"
    title: Hugo-Mainroad
    subtitle: "Just Another Site ..."
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - sidemenu
      - search
      - recent
      - categories
      - taglist
  widgets:
    recent_num: 5
    categories_counter: false
    tags_counter: false
    search:
      cached: true
      url: https://google.com/search
      input:
        name: sitesearch

menus:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: 'Blog'
      pageRef: /blog
      identifier: 'blog'
      weight: 20
    - name: "Bible Study Notebook"
      pageRef: /notebook
      identifier: 'notebook'
      weight: 30
#  side:
  footer:
    - name: Home
      PageRef: /
      weight: 1
    - name: Contact
      PageRef: '/contact/'
      weight: 20
    - name: 'Privacy Policy'
      PageRef: '/privacy/'
      weight: 30
    - name: 'Terms and Conditions'
      PageRef: '/terms/'
      weight: 40
